-- TOHID-AI WhatsApp persistent data schema

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  session_phone text not null,
  chat_id text not null,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

-- Backward-compatible columns if the original table already exists.
alter table public.messages add column if not exists session_phone text;
alter table public.messages add column if not exists chat_id text;

create index if not exists messages_session_chat_created_idx
  on public.messages (session_phone, chat_id, created_at desc);

create table if not exists public.whatsapp_auth_creds (
  session_id text primary key,
  creds jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.whatsapp_auth_keys (
  session_id text not null,
  key_type text not null,
  key_id text not null,
  value jsonb,
  updated_at timestamptz not null default now(),
  primary key (session_id, key_type, key_id)
);

create index if not exists whatsapp_auth_keys_session_idx
  on public.whatsapp_auth_keys (session_id, key_type);

alter table public.messages enable row level security;
alter table public.whatsapp_auth_creds enable row level security;
alter table public.whatsapp_auth_keys enable row level security;

-- The backend uses the Supabase service-role key. No public policies are needed.
