-- TOHID-AI WhatsApp memory schema
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  whatsapp_number text not null,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_whatsapp_created_idx
  on public.messages (whatsapp_number, created_at desc);

alter table public.messages enable row level security;

-- Backend uses the Supabase service-role key, so no public client policies are needed.
